import os, random
random.seed(6)
OUT="korpus_baru"; os.makedirs(OUT,exist_ok=True)
D={}
D["produktivitas_kerja"]=["produktivitas kerja adalah menghasilkan nilai maksimal dengan usaha terarah.",
 "fokus pada hasil, bukan sekadar terlihat sibuk.",
 "kerjakan tugas bernilai tinggi di jam energi terbaikmu.",
 "batch tugas serupa untuk mengurangi beban pindah konteks.",
 "rapat yang efektif punya agenda dan batas waktu jelas.",
 "otomatiskan pekerjaan repetitif bila memungkinkan.",
 "istirahat teratur menjaga kualitas kerja sepanjang hari.",
 "tinjau prioritas setiap pagi untuk memulai dengan benar."]
D["habit_building"]=["kebiasaan terbentuk dari pengulangan kecil yang konsisten.",
 "mulai dari versi terkecil agar mudah dimulai.",
 "kaitkan kebiasaan baru dengan rutinitas yang sudah ada.",
 "lingkungan yang mendukung mempermudah kebiasaan baik.",
 "lacak kemajuan untuk menjaga motivasi.",
 "jangan putus rantai: konsistensi mengalahkan intensitas.",
 "saat gagal sehari, segera kembali di hari berikutnya.",
 "identitas baru tumbuh dari kebiasaan yang diulang."]
D["deep_work"]=["deep work adalah fokus mendalam tanpa gangguan untuk kerja bernilai tinggi.",
 "blok waktu khusus melindungi sesi fokus.",
 "matikan notifikasi selama deep work.",
 "satu tugas per sesi agar pikiran tidak terpecah.",
 "ritual awal membantu masuk ke kondisi fokus.",
 "deep work menghasilkan kualitas yang sulit ditiru.",
 "jadwalkan deep work di jam puncak energimu.",
 "pulih dengan istirahat agar fokus berkelanjutan."]
D["belajar_efektif"]=["belajar efektif memakai teknik yang terbukti secara riset.",
 "active recall: uji dirimu alih-alih membaca ulang.",
 "spaced repetition mengulang materi dengan jeda bertahap.",
 "jelaskan kembali dengan kata-katamu sendiri.",
 "pecah materi kompleks menjadi bagian kecil.",
 "belajar dalam sesi singkat berkala lebih baik daripada maraton.",
 "tidur setelah belajar memperkuat ingatan.",
 "variasi contoh memperdalam pemahaman konsep."]
D["membaca_cepat"]=["membaca cepat adalah keterampilan menyerap informasi lebih efisien.",
 "gunakan penunjuk jari atau kursor untuk memandu mata.",
 "kurangi subvokalisasi agar kecepatan meningkat.",
 "perluas jangkauan pandangan per fiksasi.",
 "skim dulu struktur sebelum membaca detail.",
 "sesuaikan kecepatan dengan tujuan membaca.",
 "latihan rutin menaikkan kecepatan tanpa kehilangan pemahaman.",
 "tidak semua bagian perlu dibaca sama rata."]
D["mencatat"]=["mencatat membantu memahami dan mengingat informasi.",
 "tulis dengan kata-kata sendiri, bukan menyalin.",
 "metode cornell memisahkan catatan, kata kunci, dan ringkasan.",
 "mind map cocok untuk materi yang bercabang.",
 "catat poin utama, bukan semua kata.",
 "tinjau catatan dalam 24 jam untuk memperkuat ingatan.",
 "gunakan simbol dan singkatan konsisten.",
 "catatan rapi adalah aset belajar jangka panjang."]
D["goal_setting"]=["tujuan yang jelas memberi arah pada usahamu.",
 "buat tujuan spesifik dan terukur.",
 "pecah tujuan besar menjadi target mingguan.",
 "tetapkan tenggat agar ada rasa urgensi.",
 "tinjau kemajuan secara berkala dan sesuaikan.",
 "rayakan pencapaian kecil untuk menjaga semangat.",
 "tujuan tertulis lebih mungkin tercapai.",
 "selaraskan tujuan harian dengan visi besarmu."]
D["refleksi_diri"]=["refleksi diri adalah meninjau pengalaman untuk belajar darinya.",
 "luangkan waktu rutin untuk merenung tanpa gangguan.",
 "tanyakan apa yang berjalan baik dan apa yang bisa diperbaiki.",
 "jurnal refleksi merekam pertumbuhan dari waktu ke waktu.",
 "jujur pada diri sendiri adalah kunci refleksi bermakna.",
 "refleksi mengubah pengalaman menjadi kebijaksanaan.",
 "gunakan refleksi untuk menyelaraskan tindakan dan nilai.",
 "refleksi teratur meningkatkan kesadaran diri."]
D["literasi_digital"]=["literasi digital adalah kemampuan menggunakan teknologi secara bijak.",
 "verifikasi informasi sebelum mempercayai dan membagikan.",
 "kenali ciri hoaks: judul provokatif dan sumber tidak jelas.",
 "lindungi data pribadi di dunia maya.",
 "pahami jejak digital yang kamu tinggalkan.",
 "gunakan teknologi untuk belajar dan berkarya.",
 "hargai privasi dan karya orang lain di internet.",
 "literasi digital adalah keterampilan hidup modern."]
D["keamanan_akun"]=["keamanan akun melindungi identitas dan datamu.",
 "gunakan kata sandi unik dan kuat untuk tiap akun.",
 "aktifkan autentikasi dua langkah di akun penting.",
 "waspadai phishing yang meminta data pribadi.",
 "perbarui perangkat dan aplikasi secara rutin.",
 "jangan bagikan kode otp kepada siapa pun.",
 "periksa aktivitas login yang mencurigakan.",
 "gunakan pengelola kata sandi untuk kemudahan aman."]
D["backup_data"]=["backup data adalah salinan cadangan untuk mengantisipasi kehilangan.",
 "terapkan aturan tiga dua satu: tiga salinan, dua media, satu offsite.",
 "jadwalkan backup otomatis agar tidak terlupa.",
 "uji proses pemulihan untuk memastikan backup berfungsi.",
 "enkripsi backup yang berisi data sensitif.",
 "backup sebelum melakukan perubahan besar.",
 "simpan satu salinan di lokasi terpisah.",
 "data yang tidak dibackup adalah data yang siap hilang."]
D["cloud_storage"]=["cloud storage menyimpan data di server yang dapat diakses dari mana saja.",
 "pilih penyedia dengan reputasi keamanan baik.",
 "sinkronisasi otomatis menjaga file selalu terkini.",
 "atur berbagi tautan dengan hati-hati.",
 "gunakan enkripsi untuk data sensitif.",
 "perhatikan batas penyimpanan paket gratis.",
 "cloud mempermudah kolaborasi tim.",
 "tetap miliki backup lokal sebagai cadangan."]
D["open_source"]=["open source adalah perangkat lunak dengan kode terbuka untuk publik.",
 "siapa pun dapat mempelajari, memakai, dan berkontribusi.",
 "lisensi mengatur hak dan kewajiban pengguna kode.",
 "berkontribusi open source membangun portofolio dan jejaring.",
 "proyek besar seperti linux lahir dari kolaborasi terbuka.",
 "laporkan bug dan dokumentasi adalah kontribusi berharga.",
 "open source mempercepat inovasi bersama.",
 "hormati lisensi saat memakai kode orang lain."]
D["tools_ai_gratis"]=["banyak tools ai gratis tersedia untuk produktivitas.",
 "chatbot ai membantu riset dan brainstorming ide.",
 "tools ringkasan mempercepat memahami dokumen panjang.",
 "generator gambar gratis mendukung kebutuhan desain.",
 "asisten penulisan membantu memperbaiki tata bahasa.",
 "periksa kebijakan privasi sebelum mengunggah data.",
 "gunakan ai sebagai alat bantu, bukan pengganti berpikir.",
 "eksplorasi berbagai tools untuk menemukan yang cocok."]
D["aplikasi_produktif"]=["aplikasi produktif membantu mengatur tugas dan waktu.",
 "manajer tugas seperti to-do list menjaga fokus prioritas.",
 "kalender digital menyatukan jadwal dan pengingat.",
 "aplikasi catatan menangkap ide kapan saja.",
 "timer pomodoro mendukung sesi kerja fokus.",
 "pilih sedikit aplikasi dan kuasai, jangan kebanyakan.",
 "sinkronisasi antar perangkat menjaga kelancaran.",
 "evaluasi rutin apakah aplikasi benar-benar membantu."]
D["internet_sehat"]=["internet sehat adalah penggunaan internet yang positif dan aman.",
 "batasi waktu layar agar seimbang dengan dunia nyata.",
 "konsumsi konten yang memperkaya, bukan menguras.",
 "jaga sopan santun dalam berinteraksi online.",
 "hindari berbagi informasi pribadi berlebihan.",
 "istirahat dari media sosial bila terasa melelahkan.",
 "gunakan internet untuk belajar dan berkarya.",
 "keseimbangan digital menjaga kesehatan mental."]
D["fotografi"]=["fotografi adalah seni menangkap cahaya menjadi gambar.",
 "komposisi rule of thirds membuat foto lebih menarik.",
 "perhatikan arah dan kualitas cahaya.",
 "fokus pada subjek dan biarkan latar mendukung.",
 "eksposur diatur oleh aperture, shutter, dan iso.",
 "ambil banyak sudut untuk menemukan yang terbaik.",
 "editing sederhana sering cukup untuk hasil bagus.",
 "latihan mata lebih penting daripada alat mahal."]
D["videografi"]=["videografi adalah seni merekam gambar bergerak menjadi cerita.",
 "stabilkan kamera agar hasil tidak goyang.",
 "rencanakan shot list sebelum merekam.",
 "audio yang jernih sama pentingnya dengan gambar.",
 "variasikan angle: wide, medium, close-up.",
 "pencahayaan menentukan mood video.",
 "edit dengan ritme yang mendukung cerita.",
 "cerita yang kuat mengalahkan gear mahal."]
D["editing_video"]=["editing video menyusun klip menjadi cerita yang utuh.",
 "potong bagian yang tidak perlu agar tetap padat.",
 "gunakan cut pada gerakan agar transisi halus.",
 "musik dan sound effect memperkuat emosi.",
 "color grading menyatukan tone visual.",
 "jaga durasi sesuai platform dan audiens.",
 "tonton hasil dari sudut penonton sebelum final.",
 "organisasi file mempermudah proses editing."]
D["desain_grafis"]=["desain grafis menyampaikan pesan lewat visual.",
 "prinsip dasar: kontras, keseimbangan, dan hierarki.",
 "batasi palet warna agar konsisten.",
 "tipografi yang tepat memperkuat karakter desain.",
 "ruang kosong membantu fokus pada elemen utama.",
 "desain untuk audiens, bukan sekadar selera pribadi.",
 "grid menjaga kerapian tata letak.",
 "simpel sering kali lebih kuat daripada ramai."]
D["ilustrasi"]=["ilustrasi adalah gambar yang mendukung atau menceritakan ide.",
 "mulai dengan sketsa kasar untuk eksplorasi.",
 "bentuk sederhana bisa menyampaikan emosi kuat.",
 "warna membangun suasana dan fokus.",
 "gaya personal tumbuh dari latihan konsisten.",
 "pelajari anatomi dan perspektif secara bertahap.",
 "referensi membantu, tapi kembangkan suaramu sendiri.",
 "ilustrasi digital mempermudah revisi dan eksperimen."]
D["musik_produksi"]=["musik produksi adalah proses menciptakan dan merekam musik.",
 "daw adalah perangkat lunak inti produksi musik.",
 "mulai dari ide sederhana lalu kembangkan bertahap.",
 "arrangement menjaga lagu tetap menarik dari awal sampai akhir.",
 "mixing menyeimbangkan elemen suara.",
 "mastering menyiapkan lagu untuk distribusi.",
 "referensi lagu sejenis membantu kalibrasi suara.",
 "selesaikan lagu lebih penting daripada sempurna."]
D["podcasting"]=["podcast adalah konten audio yang bisa dikonsumsi kapan saja.",
 "pilih topik yang kamu kuasai dan cintai.",
 "audio jernih adalah syarat utama kenyamanan pendengar.",
 "struktur episode membantu alur yang enak diikuti.",
 "konsistensi rilis membangun audiens setia.",
 "promosikan lewat media sosial dan komunitas.",
 "wawancara narasumber memperkaya konten.",
 "dengarkan kembali untuk terus memperbaiki kualitas."]
D["blogging"]=["blog adalah media tulisan pribadi di internet.",
 "pilih niche agar mudah ditemukan pembaca setia.",
 "tulis judul yang jelas dan menjanjikan nilai.",
 "konten evergreen terus mendatangkan pembaca lama.",
 "jadwal rutin membangun kebiasaan menulis dan audiens.",
 "optimasi seo dasar agar mudah ditemukan.",
 "berinteraksi dengan pembaca membangun komunitas.",
 "blog adalah portofolio menulis yang hidup."]
D["budgeting_pribadi"]=["budgeting adalah rencana alokasi pendapatan ke pos pengeluaran.",
 "catat semua pengeluaran untuk melihat pola.",
 "gunakan aturan sederhana seperti lima puluh tiga puluh dua puluh.",
 "prioritaskan kebutuhan sebelum keinginan.",
 "sisihkan tabungan di awal, bukan sisa.",
 "tinjau budget setiap bulan dan sesuaikan.",
 "dana hiburan tetap perlu agar konsisten.",
 "budget yang realistis lebih mudah dijalankan."]
D["dana_darurat"]=["dana darurat adalah cadangan untuk kejadian tak terduga.",
 "idealnya tiga hingga enam kali pengeluaran bulanan.",
 "simpan di tempat likuid yang mudah dicairkan.",
 "bangun bertahap, mulai dari nominal kecil.",
 "gunakan hanya untuk kebutuhan mendesak sesungguhnya.",
 "dana darurat berbeda dari dana investasi.",
 "otomatiskan transfer agar konsisten terisi.",
 "dana darurat memberi ketenangan pikiran."]
D["asuransi_dasar"]=["asuransi memindahkan risiko finansial ke perusahaan asuransi.",
 "asuransi kesehatan melindungi dari biaya medis besar.",
 "pahami premi, manfaat, dan pengecualian polis.",
 "pilih sesuai kebutuhan, bukan sekadar ikut-ikutan.",
 "asuransi jiwa penting bagi pencari nafkah.",
 "bandingkan produk sebelum memutuskan.",
 "bacalah polis dengan teliti sebelum tanda tangan.",
 "asuransi adalah bagian dari perencanaan keuangan."]
D["pajak_dasar"]=["pajak adalah kontribusi wajib kepada negara.",
 "penghasilan kena pajak dilaporkan melalui spt tahunan.",
 "pahami penghasilan tidak kena pajak dan tarif berlaku.",
 "simpan bukti potong untuk pelaporan.",
 "lapor tepat waktu agar terhindar dari denda.",
 "manfaatkan fasilitas pajak yang sah.",
 "konsultan pajak membantu kasus yang kompleks.",
 "melek pajak adalah bagian dari literasi keuangan."]
D["frugal_living"]=["frugal living adalah hidup hemat dengan kesadaran, bukan pelit.",
 "beli berdasarkan nilai dan kebutuhan, bukan gengsi.",
 "bedakan keinginan sesaat dan kebutuhan nyata.",
 "masak sendiri sering lebih hemat dan sehat.",
 "manfaatkan diskon dengan bijak, bukan impulsif.",
 "investasikan sisa hemat untuk masa depan.",
 "kualitas hidup tidak selalu sebanding dengan pengeluaran.",
 "frugal memberi kebebasan finansial jangka panjang."]
D["side_income"]=["side income adalah penghasilan tambahan di luar pekerjaan utama.",
 "mulai dari keterampilan yang sudah kamu punya.",
 "pilih yang fleksibel agar tidak mengganggu kerja utama.",
 "freelance, jual produk, atau konten adalah opsi umum.",
 "kelola waktu agar tidak kelelahan.",
 "pisahkan keuangan side income dari gaji utama.",
 "scale perlahan saat hasil mulai konsisten.",
 "side income mempercepat tujuan finansial."]
D["manajemen_utang"]=["manajemen utang adalah mengendalikan pinjaman agar sehat.",
 "hindari utang konsumtif untuk gaya hidup.",
 "prioritaskan lunasi utang berbunga tinggi.",
 "jangan gali lubang tutup lubang.",
 "rasio cicilan ideal di bawah tiga puluh persen pendapatan.",
 "negosiasikan restrukturisasi bila kesulitan.",
 "utang produktif bisa membantu bila terkelola.",
 "bebas utang memberi ruang finansial yang lega."]
D["perencanaan_keuangan"]=["perencanaan keuangan adalah peta menuju tujuan finansial.",
 "mulai dari mencatat arus kas dan neraca pribadi.",
 "tetapkan tujuan jangka pendek, menengah, panjang.",
 "bangun dana darurat sebelum berinvestasi.",
 "diversifikasi investasi sesuai profil risiko.",
 "tinjau rencana secara berkala.",
 "disiplin lebih penting daripada besarnya modal awal.",
 "perencanaan memberi ketenangan dan arah."]
D["etika_bermedia"]=["etika bermedia adalah norma berperilaku di media sosial.",
 "saring sebelum sharing: verifikasi kebenarannya.",
 "hormati privasi dan martabat orang lain.",
 "hindari ujaran kebencian dan perundungan.",
 "berdebatlah dengan ide, bukan menyerang pribadi.",
 "hargai karya dengan memberi kredit.",
 "jejak digital sulit dihapus, berpikir sebelum unggah.",
 "media yang sehat dimulai dari pengguna yang bijak."]
D["netiket"]=["netiket adalah tata krama berinteraksi di internet.",
 "perlakukan orang online seperti tatap muka.",
 "hormati waktu dan perhatian orang lain.",
 "gunakan bahasa yang sopan dan jelas.",
 "jangan menyebar spam atau chain message.",
 "maafkan kesalahan orang baru di komunitas.",
 "jaga identitas pribadi dan orang lain.",
 "netiket membuat internet lebih nyaman untuk semua."]
D["budaya_indonesia"]=["indonesia memiliki kekayaan budaya yang luar biasa.",
 "ratusan suku bangsa dengan tradisi masing-masing.",
 "batik diakui unesco sebagai warisan budaya dunia.",
 "wayang adalah seni pertunjukan filosofis yang tua.",
 "gotong royong menjadi nilai inti masyarakat.",
 "bahasa daerah memperkaya identitas nusantara.",
 "upacara adat mewarnai siklus kehidupan.",
 "melestarikan budaya adalah tanggung jawab bersama."]
D["kuliner_nusantara"]=["kuliner nusantara kaya rasa dan beragam.",
 "rendang dinobatkan sebagai makanan terlezat dunia.",
 "soto punya banyak varian di tiap daerah.",
 "sambal adalah pelengkap wajib meja makan indonesia.",
 "gado-gado menampilkan kesegaran sayuran berbumbu kacang.",
 "nasi goreng adalah hidangan sejuta umat.",
 "tiap daerah punya signature dish yang unik.",
 "kuliner adalah bagian penting pariwisata indonesia."]
D["wisata_indonesia"]=["indonesia surga wisata alam dan budaya.",
 "bali terkenal dengan pantai dan budayanya.",
 "raja ampat surga bawah laut kelas dunia.",
 "borobudur candi buddha terbesar di dunia.",
 "bromo dan ijen menawarkan panorama vulkanik.",
 "yogyakarta pusat budaya dan kuliner.",
 "danau toba danau vulkanik terbesar.",
 "wisata indonesia terus berkembang dengan infrastruktur baru."]
D["tradisi_nusantara"]=["tradisi nusantara mencerminkan kearifan lokal.",
 "sekaten adalah perayaan budaya di yogyakarta dan solo.",
 "ngaben adalah upacara kremasi di bali.",
 "pasola adalah tradisi perang-perangan di sumba.",
 "tabuik adalah festival peringatan di pariaman.",
 "batik tiap daerah punya motif bermakna.",
 "tradisi lisan menjaga cerita turun-temurun.",
 "merawat tradisi menjaga identitas bangsa."]
D["bahasa_daerah"]=["indonesia punya ratusan bahasa daerah.",
 "bahasa jawa adalah bahasa daerah dengan penutur terbanyak.",
 "bahasa sunda, minang, dan bali juga kaya sastra.",
 "tiap bahasa menyimpan kearifan dan dunia pandang.",
 "pelestarian bahasa daerah penting bagi identitas.",
 "bahasa daerah memperkaya bahasa indonesia.",
 "banyak bahasa daerah terancam punah.",
 "mempelajari bahasa daerah menghubungkan dengan akar."]
D["seni_rupa"]=["seni rupa adalah ekspresi visual berbentuk karya.",
 "unsur seni rupa: garis, bentuk, warna, tekstur.",
 "seni rupa murni untuk ekspresi, terapan untuk fungsi.",
 "lukisan, patung, dan grafis adalah medium klasik.",
 "seni kontemporer membuka batas medium dan ide.",
 "apresiasi seni melatih kepekaan visual.",
 "seni rupa indonesia kaya dari tradisi hingga modern.",
 "berkarya seni adalah cara berkomunikasi tanpa kata."]

def buat(nama,kl,target=30000):
    blok=[]
    for k in kl: blok.append(k)
    for k in kl:
        q=k.split(" adalah ")[0].strip() if " adalah " in k else k.split(".")[0].strip()
        blok.append(f"tanya: apa itu {q.lower()}?\njawab: {k}")
    for k in kl: blok.append(f"fakta: {k}")
    out=[];tot=0;i=0
    while tot<target:
        b=blok[i%len(blok)];out.append(b);tot+=len(b)+2;i+=1
        if i>len(blok)*60: break
    random.shuffle(out)
    open(os.path.join(OUT,f"{nama}.txt"),"w",encoding="utf-8").write("\n\n".join(out))
for n,k in D.items(): buat(n,k)
print("part B:", len(D), "otak siap")
