import os, random
random.seed(5)
OUT="korpus_baru"; os.makedirs(OUT,exist_ok=True)
D={}
D["unpad"]=["universitas padjadjaran atau unpad adalah perguruan tinggi negeri di jawa barat.",
 "kampus utama unpad berlokasi di jatinangor, kabupaten sumedang.",
 "unpad didirikan pada tahun 1957 dan menjadi salah satu universitas tertua di indonesia.",
 "unpad punya fakultas lengkap dari kedokteran, hukum, ekonomi, hingga ilmu komunikasi.",
 "jatinangor dikenal sebagai kota mahasiswa karena banyaknya kampus di sekitarnya.",
 "unpad berkontribusi pada riset dan pengembangan ilmu di indonesia.",
 "banyak tokoh nasional merupakan alumni universitas padjadjaran.",
 "unpad membuka berbagai program beasiswa bagi mahasiswa berprestasi."]
D["harvard"]=["harvard university adalah universitas swasta elit di cambridge, massachusetts, amerika serikat.",
 "harvard adalah salah satu universitas tertua dan paling prestisius di dunia.",
 "harvard dikenal melahirkan banyak pemimpin dunia, pemenang nobel, dan pengusaha sukses.",
 "seleksi masuk harvard sangat kompetitif dengan tingkat penerimaan yang rendah.",
 "perpustakaan harvard adalah salah satu koleksi akademik terbesar di dunia.",
 "harvard business school dan harvard law school termasuk yang terbaik di bidangnya.",
 "budaya akademik harvard menekankan diskusi, riset, dan keunggulan intelektual.",
 "alumni harvard membentuk jaringan profesional yang sangat kuat secara global."]
D["kuliah_sukses"]=["kuliah sukses dimulai dari manajemen waktu dan disiplin belajar.",
 "hadiri perkuliahan secara rutin dan catat poin penting.",
 "bangun relasi dengan dosen dan teman untuk mendukung pembelajaran.",
 "kerjakan tugas tepat waktu agar tidak menumpuk di akhir semester.",
 "ikuti organisasi dan kegiatan kampus untuk mengembangkan soft skill.",
 "manfaatkan perpustakaan dan sumber belajar daring secara maksimal.",
 "jaga kesehatan fisik dan mental agar tetap produktif selama kuliah.",
 "tetapkan tujuan yang jelas sejak awal agar kuliah terarah."]
D["skripsi"]=["skripsi adalah karya ilmiah akhir untuk menyelesaikan studi sarjana.",
 "pilih topik skripsi yang kamu kuasai dan memiliki data yang memadai.",
 "rumuskan masalah yang jelas dan dapat diteliti.",
 "lakukan kajian pustaka untuk membangun landasan teori.",
 "konsultasi rutin dengan dosen pembimbing mempercepat proses skripsi.",
 "kelola data dengan rapi dan analisis secara sistematis.",
 "tulis secara bertahap, jangan menunggu sempurna baru menulis.",
 "latihan presentasi sebelum sidang agar lebih percaya diri."]
D["beasiswa"]=["beasiswa adalah bantuan biaya pendidikan yang tidak perlu dikembalikan.",
 "beasiswa tersedia dari pemerintah, lembaga swasta, dan universitas.",
 "persiapkan dokumen seperti transkrip, sertifikat, dan rekomendasi sejak dini.",
 "esai dan motivation letter yang kuat meningkatkan peluang lolos.",
 "jaga prestasi akademik dan kegiatan organisasi sebagai nilai tambah.",
 "ikuti tenggat pendaftaran dengan teliti karena sangat ketat.",
 "beasiswa luar negeri sering mensyaratkan kemampuan bahasa.",
 "banyak beasiswa juga menanggung biaya hidup dan tiket pesawat."]
D["studi_luar_negeri"]=["studi luar negeri membuka wawasan dan jejaring internasional.",
 "riset universitas dan program yang sesuai dengan tujuanmu.",
 "persiapkan kemampuan bahasa melalui tes seperti ielts atau toefl.",
 "urus dokumen seperti paspor, visa, dan ijazah sejak jauh hari.",
 "hitung biaya hidup dan cari opsi beasiswa untuk meringankan.",
 "beradaptasi dengan budaya baru adalah bagian dari pengalaman.",
 "jaga kesehatan dan asuransi selama di luar negeri.",
 "manfaatkan kesempatan magang dan riset internasional."]
D["organisasi_mahasiswa"]=["organisasi mahasiswa mengembangkan kepemimpinan dan kerja sama tim.",
 "pilih organisasi yang sesuai minat dan tujuan pengembangan diri.",
 "aktif berkontribusi memberi pengalaman nyata di luar kelas.",
 "organisasi melatih manajemen waktu antara akademik dan kegiatan.",
 "jejaring dari organisasi berguna untuk karir setelah lulus.",
 "ambil tanggung jawab bertahap untuk membangun kapasitas kepemimpinan.",
 "kolaborasi lintas organisasi memperluas wawasan dan relasi.",
 "jaga keseimbangan agar organisasi tidak mengganggu akademik."]
D["manajemen_waktu_kuliah"]=["manajemen waktu membantu menyeimbangkan kuliah, organisasi, dan istirahat.",
 "buat jadwal mingguan dan prioritaskan tugas terpenting.",
 "gunakan teknik membagi tugas besar menjadi langkah kecil.",
 "hindari menunda dengan memulai dari hal paling sulit.",
 "sisihkan waktu khusus untuk belajar mendalam tanpa gangguan.",
 "evaluasi penggunaan waktumu secara berkala untuk perbaikan.",
 "istilah istirahat yang cukup adalah bagian dari produktivitas.",
 "katakan tidak pada hal yang tidak sejalan dengan prioritasmu."]
D["harvest_moon"]=["harvest moon adalah seri game simulasi bertani dan kehidupan desa.",
 "pemain mengelola kebun, memelihara hewan, dan berinteraksi dengan warga.",
 "manajemen energi dan waktu penting karena setiap hari terbatas.",
 "menanam sesuai musim memaksimalkan hasil panen.",
 "membangun hubungan dengan warga membuka cerita dan hadiah.",
 "upgrade alat dan kandang mempermudah pekerjaan bertani.",
 "menambang dan memancing adalah sumber penghasilan tambahan.",
 "seri terbarunya dikenal sebagai story of seasons."]
D["god_of_war"]=["god of war adalah seri game aksi bertema mitologi.",
 "awalnya berbasis mitologi yunani, lalu beralih ke mitologi nordik.",
 "kratos adalah protagonis ikonik dengan kisah balas dendam dan penebusan.",
 "game nordik mengeksplorasi hubungan kratos dengan anaknya, atreus.",
 "pertarungan memadukan aksi brutal dengan strategi dan puzzle.",
 "naratif god of war dikenal emosional dan mendalam.",
 "leviathan axe adalah senjata ikonik yang bisa dilempar dan dipanggil.",
 "seri ini memenangkan banyak penghargaan game of the year."]
D["farming_sim"]=["game simulasi bertani mengajarkan perencanaan dan kesabaran.",
 "atur lahan, irigasi, dan jadwal tanam untuk hasil optimal.",
 "diversifikasi sumber pendapatan mempercepat kemajuan.",
 "berinteraksi dengan npc memperkaya pengalaman bermain.",
 "otomatisasi alat mengurangi pekerjaan repetitif.",
 "perhatikan cuaca dan musim dalam mengelola kebun.",
 "menabung dan berinvestasi di upgrade penting untuk ekspansi.",
 "game bertani cocok untuk relaksasi dan bermain santai."]
D["rpg_games"]=["rpg atau role-playing game menempatkan pemain sebagai karakter dalam cerita.",
 "perkembangan karakter lewat experience point dan level.",
 "pilihan dialog sering memengaruhi alur cerita.",
 "eksplorasi dunia adalah inti dari banyak rpg.",
 "sistem pertarungan bisa real-time atau bergiliran.",
 "membangun build karakter menentukan gaya bermain.",
 "quest sampingan memperkaya dunia dan lore.",
 "rpg mendorong imajinasi dan pengambilan keputusan."]
D["game_design"]=["game design adalah seni merancang pengalaman bermain.",
 "mekanik adalah aturan dan interaksi inti dalam game.",
 "level design mengarahkan pemain melalui ruang dan tantangan.",
 "keseimbangan difficulty menjaga game tetap menantang tapi adil.",
 "umpan balik instan membuat aksi terasa memuaskan.",
 "naratif dan gameplay harus saling mendukung.",
 "playtesting mengungkap masalah yang tidak terlihat perancang.",
 "desain yang baik membuat pemain terus ingin bermain."]
D["esports_pro"]=["esports adalah kompetisi game profesional tingkat tinggi.",
 "latihan terstruktur dan analisis replay meningkatkan performa.",
 "kerja sama tim dan komunikasi kunci kemenangan di game tim.",
 "kesehatan fisik dan mental memengaruhi konsistensi pemain.",
 "karir esports meliputi pemain, pelatih, analis, dan caster.",
 "turnamen besar menawarkan hadiah dan pengakuan global.",
 "disiplin dan mental juara membedakan pemain pro.",
 "esports kini diakui sebagai cabang olahraga di banyak negara."]
D["retro_games"]=["retro games adalah game klasik dari era konsol lama.",
 "era 8-bit dan 16-bit melahirkan banyak game legendaris.",
 "keterbatasan teknis justru memicu kreativitas desain.",
 "musik chiptune menjadi ciri khas game retro.",
 "banyak game retro masih dimainkan lewat emulator.",
 "game retro dihargai karena gameplay murni tanpa gimmick.",
 "koleksi konsol dan kaset retro jadi hobi populer.",
 "game modern sering terinspirasi mekanik game retro."]
D["open_world_games"]=["open world game memberi kebebasan menjelajah dunia luas.",
 "pemain memilih urutan misi sesuai keinginan.",
 "dunia hidup dengan npc dan aktivitas sampingan.",
 "eksplorasi memberi hadiah dan rahasia tersembunyi.",
 "sistem fast travel mempermudah perpindahan jarak jauh.",
 "cerita utama dan sampingan saling melengkapi.",
 "game open world mendorong rasa penasaran.",
 "contoh terkenalnya termasuk seri yang fokus pada eksplorasi."]
D["tata_bahasa"]=["tata bahasa adalah aturan struktur kalimat yang benar.",
 "kalimat efektif punya subjek dan predikat yang jelas.",
 "gunakan imbuhan secara tepat agar makna tidak berubah.",
 "tanda baca membantu memperjelas maksud kalimat.",
 "hindari pemborosan kata dalam menulis.",
 "kalimat baku penting untuk dokumen resmi dan akademik.",
 "konsistensi ejaan menjaga profesionalitas tulisan.",
 "membaca banyak membantu menginternalisasi tata bahasa."]
D["cara_ngomong"]=["cara ngomong yang baik dimulai dari kejelasan dan ketulusan.",
 "bicara dengan tempo sedang agar mudah dipahami.",
 "kontak mata menunjukkan keyakinan dan perhatian.",
 "sesuaikan bahasa dengan lawan bicara dan situasi.",
 "dengarkan lebih banyak sebelum berbicara.",
 "struktur pesan: pembukaan, isi, penutup agar runtut.",
 "hindari filler berlebihan seperti eee yang mengganggu.",
 "latihan rutin membuat cara bicara makin natural."]
D["wawancara_kerja"]=["wawancara kerja adalah kesempatan menunjukkan kecocokan dengan perusahaan.",
 "riset perusahaan dan posisi sebelum wawancara.",
 "siapkan jawaban untuk pertanyaan umum dengan metode star.",
 "ceritakan pencapaian dengan data dan dampak nyata.",
 "tunjukkan antusiasme dan sikap profesional.",
 "ajukan pertanyaan cerdas tentang peran dan budaya.",
 "datang tepat waktu dan berpakaian rapi.",
 "kirim ucapan terima kasih setelah wawancara."]
D["nulis_cv"]=["cv adalah ringkasan pengalaman dan keterampilan untuk melamar kerja.",
 "buat cv maksimal satu hingga dua halaman.",
 "awali dengan ringkasan profil yang kuat dan relevan.",
 "tonjolkan pencapaian dengan angka, bukan hanya tugas.",
 "sesuaikan cv dengan posisi yang dilamar.",
 "gunakan format bersih dan mudah dibaca ats.",
 "cantumkan keterampilan yang benar-benar kamu kuasai.",
 "periksa typo sebelum mengirim cv."]
D["surat_lamaran"]=["surat lamaran memperkenalkan dirimu kepada perusahaan.",
 "sebutkan posisi yang dilamar dan sumber informasinya.",
 "jelaskan mengapa kamu cocok dan apa kontribusimu.",
 "tunjukkan bahwa kamu memahami perusahaan tersebut.",
 "jaga surat tetap singkat, satu halaman idealnya.",
 "gunakan bahasa formal tapi tidak kaku.",
 "akhiri dengan ajakan untuk bertemu atau wawancara.",
 "personalisasi setiap surat, jangan template massal."]
D["email_profesional"]=["email profesional mencerminkan citra dirimu.",
 "gunakan subjek yang jelas dan spesifik.",
 "sapa dengan hormat dan perkenalkan diri bila perlu.",
 "tulis isi singkat, langsung ke inti.",
 "gunakan bahasa sopan dan bebas typo.",
 "akhiri dengan penutup dan tanda tangan profesional.",
 "periksa lampiran sebelum mengirim.",
 "balas email dalam waktu yang wajar."]
D["presentasi"]=["presentasi yang baik menyampaikan pesan dengan jelas dan menarik.",
 "mulai dengan pembuka yang menangkap perhatian.",
 "satu slide satu gagasan agar tidak membingungkan.",
 "gunakan visual sederhana yang mendukung pesan.",
 "latihan berulang mengurangi gugup dan memperbaiki alur.",
 "kontak mata dengan audiens membangun koneksi.",
 "tutup dengan kesimpulan dan ajakan yang kuat.",
 "antisipasi pertanyaan dan siapkan jawaban."]
D["bahasa_baku"]=["bahasa baku adalah ragam bahasa yang sesuai kaidah resmi.",
 "digunakan dalam dokumen resmi, akademik, dan formal.",
 "ejaan mengikuti pedoman umum ejaan yang disempurnakan.",
 "pilihan kata baku menghindari kesan santai berlebihan.",
 "kalimat baku jelas subjek predikat objeknya.",
 "hindari singkatan tidak resmi dalam tulisan formal.",
 "konsistensi istilah penting dalam karya ilmiah.",
 "menguasai bahasa baku meningkatkan kredibilitas."]
D["small_talk"]=["small talk adalah obrolan ringan untuk membangun keakraban.",
 "mulai dari topik netral seperti cuaca atau kegiatan.",
 "tunjukkan ketertarikan dengan pertanyaan terbuka.",
 "dengarkan aktif dan respons dengan antusias.",
 "hindari topik sensitif seperti politik di awal.",
 "senyum dan bahasa tubuh ramah membuka suasana.",
 "small talk adalah pintu menuju percakapan lebih dalam.",
 "latihan membuat small talk terasa natural."]
D["bikin_website"]=["membuat website kini bisa tanpa biaya besar.",
 "mulai dengan menentukan tujuan dan audiens situs.",
 "pilih platform: cms, static site, atau website builder.",
 "daftar domain dan hosting sesuai kebutuhan.",
 "desain sederhana dan responsif lebih penting dari rumit.",
 "optimalkan kecepatan dan navigasi yang jelas.",
 "isi dengan konten berkualitas dan perbarui berkala.",
 "publikasikan dan promosikan melalui media sosial."]
D["web_gratis"]=["banyak layanan gratis untuk membangun kehadiran online.",
 "github pages menyediakan hosting gratis untuk situs statis.",
 "netlify dan vercel menawarkan deploy gratis yang mudah.",
 "wordpress.com memberi platform blog gratis.",
 "canva gratis untuk membuat aset desain.",
 "google sites cocok untuk situs sederhana cepat.",
 "gunakan subdomain gratis saat belum siap beli domain.",
 "manfaatkan ssl gratis agar situs aman https."]
D["html_css"]=["html adalah kerangka struktur halaman web.",
 "css mengatur tampilan dan gaya elemen halaman.",
 "tag html mendefinisikan elemen seperti judul dan paragraf.",
 "selektor css memilih elemen untuk diberi gaya.",
 "flexbox dan grid mempermudah tata letak responsif.",
 "media query membuat situs adaptif di berbagai layar.",
 "validasi kode agar bebas error dan aksesibel.",
 "latihan membangun proyek kecil mempercepat penguasaan."]
D["javascript_dasar"]=["javascript adalah bahasa pemrograman untuk interaktivitas web.",
 "variabel menyimpan data yang bisa berubah.",
 "fungsi mengelompokkan logika yang dapat dipakai ulang.",
 "dom memungkinkan javascript mengubah isi halaman.",
 "event listener merespons aksi pengguna seperti klik.",
 "array dan objek menyimpan kumpulan data.",
 "asinkron dengan fetch mengambil data dari server.",
 "latihan manipulasi dom memperkuat pemahaman javascript."]
D["hosting_gratis"]=["hosting gratis cocok untuk proyek belajar dan portofolio.",
 "github pages ideal untuk situs statis dan dokumentasi.",
 "vercel dan netlify mendukung deploy otomatis dari git.",
 "perhatikan batasan bandwidth dan penyimpanan layanan gratis.",
 "untuk aplikasi dinamis pertimbangkan tier gratis cloud.",
 "pastikan layanan mendukung ssl agar aman.",
 "backup kontenmu karena layanan gratis bisa berubah kebijakan.",
 "naikkan ke berbayar saat trafik mulai besar."]
D["cms_wordpress"]=["wordpress adalah cms paling populer untuk membuat website.",
 "tanpa perlu kode mendalam, situs bisa cepat jadi.",
 "tema mengatur tampilan, plugin menambah fungsi.",
 "pilih plugin seperlunya agar situs tetap cepat.",
 "perbarui inti, tema, dan plugin untuk keamanan.",
 "backup rutin melindungi dari kehilangan data.",
 "seo plugin membantu optimasi mesin pencari.",
 "wordpress cocok untuk blog, toko, dan company profile."]
D["seo_dasar"]=["seo adalah optimasi agar situs mudah ditemukan mesin pencari.",
 "riset kata kunci yang relevan dengan kontenmu.",
 "tulis judul dan meta description yang menarik.",
 "struktur heading yang rapi membantu pemahaman mesin pencari.",
 "kecepatan situs memengaruhi peringkat dan pengalaman.",
 "tautan internal dan eksternal memperkuat otoritas.",
 "konten berkualitas adalah fondasi seo terbaik.",
 "pantau performa lewat alat analitik pencarian."]
D["desain_web"]=["desain web menggabungkan estetika dan kegunaan.",
 "hierarki visual mengarahkan mata pengguna.",
 "gunakan warna dan kontras yang konsisten.",
 "tipografi yang mudah dibaca meningkatkan kenyamanan.",
 "ruang putih memberi napas pada tata letak.",
 "desain responsif wajib untuk pengguna mobile.",
 "uji kegunaan dengan pengguna nyata.",
 "desain sederhana sering lebih efektif daripada ramai."]
D["github_pages"]=["github pages menyediakan hosting gratis langsung dari repositori.",
 "cocok untuk dokumentasi, portofolio, dan situs statis.",
 "aktifkan pages di pengaturan repositori.",
 "pilih branch dan folder sumber yang benar.",
 "dukung custom domain jika punya domain sendiri.",
 "deploy otomatis setiap push ke branch sumber.",
 "gratis dengan ssl otomatis.",
 "ideal untuk menampilkan proyek kepada perekrut."]
D["linkedin"]=["linkedin adalah jejaring profesional terbesar di dunia.",
 "lengkapi profil dengan ringkasan dan pengalaman yang kuat.",
 "gunakan foto profesional dan headline yang jelas.",
 "bagikan wawasan untuk membangun personal brand.",
 "terhubung dengan rekan industri memperluas peluang.",
 "rekomendasi dan endorsemen menambah kredibilitas.",
 "ikuti perusahaan dan diskusi relevan di bidangmu.",
 "linkedin sering jadi sumber rekruter menemukan kandidat."]
D["networking"]=["networking adalah membangun hubungan profesional yang saling menguntungkan.",
 "mulai dari komunitas dan acara di bidangmu.",
 "beri nilai terlebih dahulu sebelum meminta bantuan.",
 "jaga komunikasi secara berkala, bukan hanya saat butuh.",
 "dengarkan dengan tulus dan ingat detail tentang orang.",
 "tindak lanjuti pertemuan dengan pesan singkat.",
 "jejaring yang kuat membuka pintu peluang tak terduga.",
 "kualitas hubungan lebih penting dari kuantitas."]
D["negosiasi_gaji"]=["negosiasi gaji dimulai dari riset kisaran pasar untuk posisimu.",
 "sebutkan angka berdasarkan data dan kontribusimu.",
 "fokus pada nilai yang kamu bawa, bukan kebutuhan pribadi.",
 "jangan terburu menerima tawaran pertama.",
 "pertimbangkan paket keseluruhan: tunjangan, bonus, fleksibilitas.",
 "bersikap profesional dan kolaboratif, bukan konfrontatif.",
 "latihan menyampaikan argumen dengan percaya diri.",
 "siap berjalan pergi bila tawaran jauh di bawah nilai pasar."]
D["kerja_remote"]=["kerja remote memberi fleksibilitas lokasi dan waktu.",
 "ciptakan ruang kerja khusus agar fokus.",
 "komunikasi async yang jelas sangat penting.",
 "tetapkan batas jam kerja agar tidak burnout.",
 "gunakan alat kolaborasi untuk transparansi.",
 "proaktif memberi update kemajuan kepada tim.",
 "jaga koneksi internet dan perangkat andal.",
 "kerja remote menuntut disiplin dan manajemen diri tinggi."]
D["freelancing"]=["freelancing adalah bekerja mandiri dengan berbagai klien.",
 "bangun portofolio yang menunjukkan keahlianmu.",
 "tentukan niche agar mudah ditemukan klien.",
 "tetapkan harga yang mencerminkan nilai kerjamu.",
 "kontrak dan kesepakatan tertulis melindungi kedua pihak.",
 "kelola keuangan karena pendapatan tidak tetap.",
 "jaga reputasi lewat kualitas dan ketepatan waktu.",
 "platform freelance membantu menemukan klien awal."]
D["portofolio"]=["portofolio adalah kumpulan karya terbaik yang menunjukkan kemampuan.",
 "pilih karya yang relevan dengan tujuanmu.",
 "tampilkan proses dan hasil, bukan hanya hasil akhir.",
 "sertakan studi kasus dengan dampak terukur.",
 "buat versi online agar mudah dibagikan.",
 "perbarui portofolio secara berkala.",
 "minta umpan balik untuk memperbaiki presentasi karya.",
 "portofolio kuat sering lebih meyakinkan daripada ijazah."]

def buat(nama,kl,target=30000):
    blok=[]
    for k in kl: blok.append(k)
    for k in kl:
        q=k.split(" adalah ")[0].strip() if " adalah " in k else k.split(".")[0].strip()
        blok.append(f"tanya: apa itu {q.lower()}?\njawab: {k}")
    for k in kl: blok.append(f"fakta: {k}")
    out=[];tot=0;i=0
    while tot<target:
        b=blok[i%len(blok)];out.append(b);tot+=len(b)+2;i+=1
        if i>len(blok)*60: break
    random.shuffle(out)
    open(os.path.join(OUT,f"{nama}.txt"),"w",encoding="utf-8").write("\n\n".join(out))
for n,k in D.items(): buat(n,k)
print("part A:", len(D), "otak siap")
